### ISSUE TITLE
Cezerin fails to serve static content in PRODUCTION

### ISSUE THREAD

**Issue by LuBuss** [Cezerin2/Server#126]
The application is setting `Authorization` in the header, Static content and images are not getting authorization and therefore return authorization error. 

src/index.js line: 48
`	
res.header(
	'Access-Control-Allow-Headers',
	'Origin, X-Requested-With, Content-Type, Accept, Key, Authorization'
);
`

**Comment by ravitalari** [comment]
after removing the Authorization also images are not loading

**Comment by LuBuss** [comment]
Found the store was able to correctly access images as it was providing jwtSecretToken. 

Have found that API or assets are only accessible when an API token is provided.

**Comment by ngoyal16** [comment]
it needs to be fixed. in a way that.. asset can be directly accessible without any issue. and we also need to make sure every asset URL should be full URL so that admin and store will not have to append assets path and other settings.. this will give flexibility in the future. like if someone wants to change assets base location or path. then admin and store will not need to be redeployed.

**Comment by ravitalari** [comment]
URLs is now accessible with full url only. Now only issue to resolve is to
make the direct access to images. I tried access the url with /ajax as the
URI and its working

**Comment by albertusgeyser** [comment]
Good Day

Problem solved on this issue as i will go production soon.

![lintel_site](https://user-images.githubusercontent.com/31254389/56458757-dc0d3300-638a-11e9-9bb1-137710717d64.JPG)


Thank You
Albertus Geyser
