### ISSUE TITLE
Add Buttons to Product View - Feature Request

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#134]
Good Day

Add Buttons to Product view to easily add products to cart.
Each time clicked on add to cart adds one item to cart to increase qty required.

![cezerin_button](https://user-images.githubusercontent.com/31254389/56463673-4baa0f00-63d9-11e9-9bff-e555442821ea.JPG)

Thank You
Albertus Geyser

**Comment by MarcoVdE** [comment]
I wouldn't add a view product button, since clicking anywhere on the product will take you to the product page. I'd also use square buttons instead as the entire theme is modern, and only have add to cart show up on hover:
![image](https://user-images.githubusercontent.com/34270069/61814323-1f72b400-ae48-11e9-93b5-d9fb493e3bc7.png)
If you must have a view product button, then side by side is probably better.
![image](https://user-images.githubusercontent.com/34270069/61814424-59dc5100-ae48-11e9-8a91-1e7980daaa3a.png)
`border: unset;
background-color: #E0E0E0A8;
color: black;
padding: 0.3rem 1rem;
margin-top: 0.5rem;
margin-left: 0.2rem;
margin-right: 0.2rem;`
Is the styling I am using for the button, to help with quick implementation but wouldn't use margins like that to have it mostly center. Would change to Cezerin black on hover (#333333) and white text.
