### ISSUE TITLE
Cezerin2 master branch

### ISSUE THREAD

**Issue by hung1806vn** [Cezerin2/Server#61]
Cezerin2 master branch need to be most stable like the cezerin1. Any big change need to least effect on the origin

**Comment by ngoyal16** [comment]
we are separating everything so that easy to understand by developers.

like if someone wants to design a new theme they can design... based on cezerin2-store...

if they want to build their own admin theme they can build using cezerin2-theme... 

our core product is cezerin2 backend... hoping it will stable after this week because most of the separation is done

**Comment by hung1806vn** [comment]
Thank you for your support. I understood
